<a href="https://colab.research.google.com/github/ammarSherif/CIT690E-Deep-Learning-Labs/blob/main/Lab%202%3A%20Tensor%20Operations.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Lab 2: Tensor Oprations
CIT690E: Deep Learning<br>
Nile University<br>
Ammar Sherif<br>

## Acknowledgement
Kindly, notice this notebook is adapted from Eng. Ahmed's version; you can check his [GitHub repo](https://github.com/ahosnyyy/CIT690E-DL-Course).

## PyTorch
- Open-source by Facebook
- Optimized Deep Learning on GPU and CPU
- Supports Python, C++, and Java
- Products built upon it: 
    - Tesla Autopilot
    - Uber’s Pyro
    - Hugging Face’s Transformers
    - PyTorch Lightning
    - Catalyst
- Primary structure: Tensors
You can check more details in their [PyTorch Website](https://pytorch.org/) 

## PyTorch Tensors
They represent **n-dimensional arrays**. It is very similar to NumPy arrays. Therefore, we have
- scalars: `rank 0` tensors
- 1D vector: `rank 1` tensors
- 2D Matrix: `rank 2` tensors
- nth-dimentional structure: `rank n` tensors

![tensor_1](https://d3i71xaburhd42.cloudfront.net/82750a1533ca30a705d3325290ee8de471073773/3-Figure3-1.png)



In [1]:
# ==============================================================================
# Some imports
# ==============================================================================
import torch
import math

## Creating Tensors

### Empty Tensor

In [2]:
# ==============================================================================
# Below we use the empty to generate 3*4 tensor
# ==============================================================================
x = torch.empty(3, 4)
print(type(x))
print(x)

<class 'torch.Tensor'>
tensor([[-5.7061e-06,  3.0726e-41,  3.3631e-44,  0.0000e+00],
        [        nan,  3.0726e-41,  1.1578e+27,  1.1362e+30],
        [ 7.1547e+22,  4.5828e+30,  1.2121e+04,  7.1846e+22]])


**Some Notes**
- we used the `empty()` from `torch`
- we specified `3` as the number of rows and `4` as the number of columns
- the datatype is `torch.FloatTensor` by default
- the data are random, as they are in memory

### From a List

In [3]:
# ==============================================================================
# Generate a 1D tensor of the below data
# ==============================================================================
a = torch.tensor([1, 2, 3])
print(a)

tensor([1, 2, 3])


In [4]:
# ==============================================================================
# Generate 2D tensor from a 2D list
# ==============================================================================
b = torch.tensor([[1], [2], [3]])
print(b)

tensor([[1],
        [2],
        [3]])


### From a NumPy array

In [5]:
# ==============================================================================
# Import numpy creating an array; then, convert it to tensor
# ==============================================================================
import numpy as np

na = np.array([1, 2, 3])
a = torch.tensor(na)

We can also use the <font color='red'>`from_numpy`</font> function to convert a NumPy array to a PyTorch tensor. You just have to pass the NumPy array object as an argument.

In [6]:
b = torch.from_numpy(na)

### Special Tensors

- `eye()`: Identity 2D Tensor
- `ones()`: Tensor of ones of a particular shape
- `zeros()`: Tensor of zeros of a particular shape

In [7]:
# ==============================================================================
# Create a identity tensor with 3*3 shape.
# ==============================================================================
eys = torch.eye(3)
print(eys)
# ==============================================================================
# Create a tensor with 2*2 shape whose values are all 1.
# ==============================================================================
ones = torch.ones((2, 2))
print(ones)
# ==============================================================================
# Create a tensor with 3*3 shape whose values are all 0.
# ==============================================================================
zeros = torch.zeros((3, 3))
print(zeros)

tensor([[1., 0., 0.],
        [0., 1., 0.],
        [0., 0., 1.]])
tensor([[1., 1.],
        [1., 1.]])
tensor([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]])


### Random Tensors

- `rand()`: sampled from a uniform distribution
- `randn()`: sampled from a normal distribution with mean 0 and variance 1
- `randint()`: random samples of integer values in a particular range.

In [8]:
# ==============================================================================
# Create a tensor with 1*10 shape with random value between 0 and 1
r0 = torch.rand(10)
print(r0)
print("************************************************")
# Create a tensor with 10*1 shape with random value between 0 and 1
r1 = torch.rand((10, 1))
print(r1)
print("************************************************")
# Create a tensor with 2*2 shape with random value between 0 and 1
r2 = torch.rand((2, 2))
print(r2)
print("************************************************")
# Create a tensor with 2*2 shape with random value from a normal distribution.
r3 = torch.randn((2,2))
print(r3)
print("************************************************")
# Create an integer type tensor with 3*3 shape with random value between 0 and 10.
r4 = torch.randint(high=10, size=(3, 3))
print(r4)
print("************************************************")
# Create an integer type tensor with 3*3 shape with random value between 5 and 10.
r5 = torch.randint(low=5, high=10, size=(3, 3))
print(r5)

tensor([0.7182, 0.4727, 0.1787, 0.4787, 0.3208, 0.7863, 0.6366, 0.9392, 0.1751,
        0.5948])
************************************************
tensor([[0.6633],
        [0.9657],
        [0.5947],
        [0.3833],
        [0.3941],
        [0.1457],
        [0.1393],
        [0.8865],
        [0.3315],
        [0.8517]])
************************************************
tensor([[0.0945, 0.9145],
        [0.2471, 0.7188]])
************************************************
tensor([[ 1.0202,  0.7952],
        [-0.0992,  1.2636]])
************************************************
tensor([[0, 0, 5],
        [1, 9, 4],
        [2, 5, 1]])
************************************************
tensor([[9, 9, 6],
        [7, 9, 6],
        [5, 6, 8]])


#### Seeding
You can use `torch.manual_seed()` to manually select a particular seed. This is very helpful for **reproducability**. Hence, we can reproduce the results produced by a model

In [9]:
# ==============================================================================
# Manual seeding to re-produce the tensors
# ==============================================================================
torch.manual_seed(1729)
random1 = torch.rand(2, 3)
print(random1)

random2 = torch.rand(2, 3)
print(random2)

torch.manual_seed(1729)
random3 = torch.rand(2, 3)
print(random3)


tensor([[0.3126, 0.3791, 0.3087],
        [0.0736, 0.4216, 0.0691]])
tensor([[0.2332, 0.4047, 0.2162],
        [0.9927, 0.4128, 0.5938]])
tensor([[0.3126, 0.3791, 0.3087],
        [0.0736, 0.4216, 0.0691]])


In [10]:
random4 = torch.rand(2, 3)
print(random4)

tensor([[0.2332, 0.4047, 0.2162],
        [0.9927, 0.4128, 0.5938]])


### Using range
We can create a tensor from a range where the `start` is included, yet the `end` is excluded.

In [11]:
# ==============================================================================
# Use arange to generate a sequence [1-9]
# ==============================================================================
a = torch.arange(1, 10)
print(a)

tensor([1, 2, 3, 4, 5, 6, 7, 8, 9])


### From Tensor Shapes
- `torch.empty_like()`
- `torch.zeros_like()`
- `torch.ones_like()`
- `torch.rand_like()`

In [12]:
# ==============================================================================
# Generate an empty tensor whose shape is 2*2*3. 
# ==============================================================================
x = torch.empty(2, 2, 3)
print(x.shape)
print(x)

# ==============================================================================
# Now, use the above tensor, x, to create new tensors using the functions above.
# ==============================================================================
empty_like_x = torch.empty_like(x)
print(empty_like_x.shape)
print(empty_like_x)

zeros_like_x = torch.zeros_like(x)
print(zeros_like_x.shape)
print(zeros_like_x)

ones_like_x = torch.ones_like(x)
print(ones_like_x.shape)
print(ones_like_x)

rand_like_x = torch.rand_like(x)
print(rand_like_x.shape)
print(rand_like_x)

torch.Size([2, 2, 3])
tensor([[[-5.7067e-06,  3.0726e-41,  3.3631e-44],
         [ 0.0000e+00,         nan,  5.9382e-01]],

        [[ 1.1578e+27,  1.1362e+30,  7.1547e+22],
         [ 4.5828e+30,  1.2121e+04,  7.1846e+22]]])
torch.Size([2, 2, 3])
tensor([[[-5.7067e-06,  3.0726e-41,  3.3631e-44],
         [ 0.0000e+00,         nan,  1.5912e+00]],

        [[ 1.1578e+27,  1.1362e+30,  7.1547e+22],
         [ 4.5828e+30,  1.2121e+04,  7.1846e+22]]])
torch.Size([2, 2, 3])
tensor([[[0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.]]])
torch.Size([2, 2, 3])
tensor([[[1., 1., 1.],
         [1., 1., 1.]],

        [[1., 1., 1.],
         [1., 1., 1.]]])
torch.Size([2, 2, 3])
tensor([[[0.6128, 0.1519, 0.0453],
         [0.5035, 0.9978, 0.3884]],

        [[0.6929, 0.1703, 0.1384],
         [0.4759, 0.7481, 0.0361]]])


## Tensor Metadate

### Type

In [13]:
# ==============================================================================
# Use dtype to sepcify the datatype
# ==============================================================================
a = torch.tensor([1, 2, 3], dtype=torch.float)
print(a.dtype)

torch.float32


### Size

In [14]:
# ==============================================================================
# We can get the use with the use of shape or size()
# ==============================================================================
a = torch.ones((3, 4))
print(a.shape)
print(a.size())

torch.Size([3, 4])
torch.Size([3, 4])


### Dimension Number

In [15]:
# ==============================================================================
# Get the number of dimensions via ndim or dim()
# ==============================================================================
a = torch.ones((3, 4, 6))
print(a.ndim)
print(a.dim())

3
3


### Elements Number 

In [16]:
# ==============================================================================
# Use numel to get the total number of elements in a tensor
# ==============================================================================
a = torch.ones((3, 4, 6))
print(a.numel())

72


## Tensor Types

Some common types listed below:

| Data Type  | dtype | CPU tensor | GPU tensor |
| --- | --- | --- |---|
| 32-bit floating point | torch.float32/torch.float | torch.FloatTensor | torch.cuda.FloatTensor |
|64-bit floating point|torch.float64/torch.double|torch.DoubleTensor|torch.cuda.DoubleTensor|
|8-bit integer (signed)|torch.int16|torch.ShortTensor|torch.cuda.ShortTensor|
|boolean|torch.bool|torch.BoolTensor|torch.cuda.BoolTensor|

Importance of Tensor Types:

- **speed and memory usage**.<br>For example, a matrix <font color='red'>`A`</font> with size 1000x1000. If the <font color='red'>`dtype`</font> is <font color='red'>`torch.float32`</font>, this matrix would consume about **3.81MB GPU memory** (1000x1000x4bytes, each <font color='red'>`float32`</font> uses 4 bytes.). If the <font color='red'>`dtype`</font> is <font color='red'>`torch.double`</font>, this matrix would consume about **7.62MB GPU memory** (1000x1000x8bytes, each <font color='red'>`double`</font> uses 8 bytes.).

- API Requirement<br>Check this [example](https://pytorch.org/docs/stable/generated/torch.nn.CrossEntropyLoss.html).



### Tensors of particular types

- <font color='red'>`FloatTensor`</font>: float32
- <font color='red'>`IntTensor`</font>
- <font color='red'>`DoubleTensor`</font>: float64
- <font color='red'>`LongTensor`</font>


In [17]:
# ==============================================================================
# Create a tensor of floats and another one of integers
# ==============================================================================
d = torch.FloatTensor([1, 2, 3])
e = torch.IntTensor([1, 2, 3])

### Casting between tensor types

The Tensor class has the method <font color='red'>`to()`</font>, which can cast tensors into different types. To cast a tensor, call its <font color='red'>`to()`</font> method and pass the dtype as the argument, as shown in the code below.

In [18]:
b = torch.tensor([1, 2, 3], dtype=torch.float)
print("The dtype for b is {}".format(b.dtype))

c = b.to(dtype=torch.int64)
print("The dtype for c is {}".format(c.dtype))

The dtype for b is torch.float32
The dtype for c is torch.int64


**Notice**: The <font color='red'>`to()`</font> cast is **not an in-place operation**

## Accessing Elements

### Using Index

If you are already familiar with the NumPy array, you can use the same methods to select tensors by <font color='red'>`[]`</font> operations.

Take a 2-dimensional tensor as an example. Let’s consider it as a matrix.

* <font color='red'>`tensor[2, 3]`</font>: Get only one value.
* <font color='red'>`tensor[:, 1]`</font>: Get the second column from the tensor.
* <font color='red'>`tensor[1, :]`</font>: Get the second row from the tensor.
* For higher-dimensional tensors, the operations are the same. Such as <font color='red'>`tensor[:, 2, :]`</font>.

In [19]:
# ==============================================================================
# Using indexes to access values
# ==============================================================================
a = torch.arange(1, 10).reshape((3, 3))
# The output
# tensor([[1, 2, 3],
#         [4, 5, 6],
#         [7, 8, 9]])
print("The original tensor")
print(a)

print("Select only one element")
print(a[1,1])

print("Select the second column")
print(a[:, 1])

print("Select the second row.")
print(a[1, :])

The original tensor
tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])
Select only one element
tensor(5)
Select the second column
tensor([2, 5, 8])
Select the second row.
tensor([4, 5, 6])


### Using `index_select`

<font color='red'>`index_select`</font> requires the following parameters:

* The first parameter is the tensor we want to select.
* <font color='red'>`dim`</font>: It indicates the dimension in which we index.<br> In this example, the tensor is a 2-dimensions tensor. <font color='red'>`dim=0`</font> means the row, <font color='red'>`dim=1`</font> means the column.
* <font color='red'>`index`</font>: The 1-D tensor containing the indices to index.

In [20]:
a = torch.arange(1, 10).reshape((3, 3))

indices = torch.LongTensor([0, 2])
result = torch.index_select(a, dim=0, index=indices)
print(result)

tensor([[1, 2, 3],
        [7, 8, 9]])


### Using a mask

The mask tensor is <font color='red'>`BoolTensor`</font>, which identifies which elements are chosen. The <font color='red'>`shape`</font> of the mask tensor and the original tensor doesn’t need to match, but they must be broadcastable.

In short, PyTorch enables us to pass a tensor of Boolean type to <font color='red'>`masked_select`</font>, which selects desired elements from another tensor.

In [21]:
a = torch.arange(1, 10).reshape((3, 3))

mask = torch.BoolTensor([[True, False, True],
                        [False, False, True],
                        [True, False, False]])
print("The mask tensor is: \n{}".format(mask))
print("The original tensor is: \n{}".format(a))
result = torch.masked_select(a, mask)
print("The result is {}".format(result))

The mask tensor is: 
tensor([[ True, False,  True],
        [False, False,  True],
        [ True, False, False]])
The original tensor is: 
tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])
The result is tensor([1, 3, 6, 7])


## Changing the Tensor Shape

### Reshaping a tensor

`torch.reshape(t,shape)`
- `t`: the tensor holding the data to be reshaped
- `shape`: the new shape; typically a tuple: (2,4) to reshape the values into 2*4 tensor

**Notice**:
- within `shape`, we can use `-1` to let PyTorch **infer** the shape to match the number of elements<br>Check the below example 

In [22]:
a = torch.arange(1, 9)
print("The original tensor\n.")
print(a)

b = torch.reshape(a, (2, 4))
print("The reshape tensor with shape (2, 4)\n")
print(b)
# ==============================================================================
# Using -1 as a  dimension  makes the actual  dimension value  to be inferred to
# match the number of values
# ==============================================================================
c = torch.reshape(a, (2, -1))
print("The reshape tensor with shape (2, -1)\n")
print(c)

The original tensor
.
tensor([1, 2, 3, 4, 5, 6, 7, 8])
The reshape tensor with shape (2, 4)

tensor([[1, 2, 3, 4],
        [5, 6, 7, 8]])
The reshape tensor with shape (2, -1)

tensor([[1, 2, 3, 4],
        [5, 6, 7, 8]])


### Squeezing

To remove the dimensions of 1 entry; for example, having a tensor of `(3,1,2)` like below, we want to remove the 2nd dimension, as it is not needed. We do so using `squeeze`

* We can’t squeeze a dimension if the size is greater than 1.
* We can squeeze multiple dimensions simultaneously in one function call. Nevertheless, it squeezes all of the dimensions, whose entries are 1s.

**Parameters:**
* <font color='red'>`input`</font>: The tensor we want to perform squeeze on.
* <font color='red'>`dim`</font>: The dimension we want to perform squeeze on. It’s optional.<br>If not specified, it squeezes all the dimensions.

In [23]:
# ==============================================================================
# Create a tensor and squeeze it
# ==============================================================================
a = torch.ones((3, 1, 2))
print("The original shape of a is {}".format(a.shape))
print("The original a tensor is {}".format(a))

a = torch.squeeze(a, dim=1)
print("The new shape of a is {}".format(a.shape))
print("The new tensor is {}".format(a))

b = torch.ones((3,1,2,1,2))
print("The original shape of a is {}".format(b.shape))
print("The original b tensor is {}".format(b))

b = torch.squeeze(b)
print("The new shape of a is {}".format(b.shape))
print("The new tensor is {}".format(b))

The original shape of a is torch.Size([3, 1, 2])
The original a tensor is tensor([[[1., 1.]],

        [[1., 1.]],

        [[1., 1.]]])
The new shape of a is torch.Size([3, 2])
The new tensor is tensor([[1., 1.],
        [1., 1.],
        [1., 1.]])
The original shape of a is torch.Size([3, 1, 2, 1, 2])
The original b tensor is tensor([[[[[1., 1.]],

          [[1., 1.]]]],



        [[[[1., 1.]],

          [[1., 1.]]]],



        [[[[1., 1.]],

          [[1., 1.]]]]])
The new shape of a is torch.Size([3, 2, 2])
The new tensor is tensor([[[1., 1.],
         [1., 1.]],

        [[1., 1.],
         [1., 1.]],

        [[1., 1.],
         [1., 1.]]])


### Un-squeezing
The reverse of `squeeze()`, adding dimensions of 1.
**Parameters:**
* <font color='red'>`dim`</font>: This parameter indicates the index at which to insert the dimension.

In [24]:
# ==============================================================================
# Unsqueezing
# ==============================================================================
a = torch.ones((3, 3))
print("The original shape of a is {}".format(a.shape))
print("The original a tensor is {}".format(a))

a = torch.unsqueeze(a, dim=1)
print("The new shape of a is {}".format(a.shape))
print("The new tensor is {}".format(a))

The original shape of a is torch.Size([3, 3])
The original a tensor is tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]])
The new shape of a is torch.Size([3, 1, 3])
The new tensor is tensor([[[1., 1., 1.]],

        [[1., 1., 1.]],

        [[1., 1., 1.]]])


### Transposing

Transposing with respect to a particular two dimensions.

In [25]:
# ==============================================================================
# Create a tensor and transpose two dimensions
# ==============================================================================
a = torch.ones((2, 4))
print("The original shape of a is {}".format(a.shape))
print("The original tensor a is {}".format(a))

a = torch.transpose(a, 0, 1)
print("The new shape of a is {}".format(a.shape))
print("The new tensor a is {}".format(a))

b = torch.ones((2, 4, 2))
print("The original shape of b is {}".format(b.shape))
print("The original tensor b is {}".format(b))

b = torch.transpose(b, 1, 2)
print("The new shape of b is {}".format(b.shape))
print("The new tensor b is {}".format(b))

The original shape of a is torch.Size([2, 4])
The original tensor a is tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.]])
The new shape of a is torch.Size([4, 2])
The new tensor a is tensor([[1., 1.],
        [1., 1.],
        [1., 1.],
        [1., 1.]])
The original shape of b is torch.Size([2, 4, 2])
The original tensor b is tensor([[[1., 1.],
         [1., 1.],
         [1., 1.],
         [1., 1.]],

        [[1., 1.],
         [1., 1.],
         [1., 1.],
         [1., 1.]]])
The new shape of b is torch.Size([2, 2, 4])
The new tensor b is tensor([[[1., 1., 1., 1.],
         [1., 1., 1., 1.]],

        [[1., 1., 1., 1.],
         [1., 1., 1., 1.]]])


## Merging Tensors

### Concatenation

<font color='red'>`torch.cat()`</font> can concatenate a sequence of tensors in a given dimension. All tensors should have the same shape. **Notice** that concatenation happens by extending the values of a dimension. No new dimensions is created. Check the below examples for further clarification 

* <font color='red'>`tensors`</font>: A list of tensors must have the same shape.
* <font color='red'>`dim`</font>: The dimension over which the tensors are concatenated.<br>Take 2D tensors as an example, <font color='red'>`dim=0`</font> means the operation would be performed row-wise, w.r.t 1st dimension.<br><font color='red'>`dim=1`</font> means the operation would be performed column-wise, , w.r.t 2nd dimension.

In [26]:
# ==============================================================================
# Concatenating tensors
# ==============================================================================
a = torch.randn((3, 3))
print("The original tesnor a is\n {}".format(a))
result = torch.cat((a, a), dim=0)
print("The shape of concatenating (a,a) is {}".format(result.shape))
print("The new tensor is\n {}".format(result))

b = torch.randn((3, 3))
print("The original tesnor b is\n {}".format(b))
result = torch.cat((b, b), dim=1)
print("The shape of result is {}".format(result.shape))
print("The new tensor is\n {}".format(result))

The original tesnor a is
 tensor([[ 0.3645,  0.1179, -0.3338],
        [ 1.2409, -1.2293, -0.4904],
        [ 0.1263, -0.0732,  1.0363]])
The shape of concatenating (a,a) is torch.Size([6, 3])
The new tensor is
 tensor([[ 0.3645,  0.1179, -0.3338],
        [ 1.2409, -1.2293, -0.4904],
        [ 0.1263, -0.0732,  1.0363],
        [ 0.3645,  0.1179, -0.3338],
        [ 1.2409, -1.2293, -0.4904],
        [ 0.1263, -0.0732,  1.0363]])
The original tesnor b is
 tensor([[-0.5292,  0.6205,  1.7128],
        [-1.2221, -1.1406,  1.1263],
        [-1.7528, -0.5989, -2.3606]])
The shape of result is torch.Size([3, 6])
The new tensor is
 tensor([[-0.5292,  0.6205,  1.7128, -0.5292,  0.6205,  1.7128],
        [-1.2221, -1.1406,  1.1263, -1.2221, -1.1406,  1.1263],
        [-1.7528, -0.5989, -2.3606, -1.7528, -0.5989, -2.3606]])


### Stacking

<font color='red'>`torch.stack()`</font> concatenates the sequence of tensors along a **new dimension**.

For example, there are two tensors with the shape (3, 4). We stack these two tensors with <font color='red'>`dim=1`</font>, then the shape of the return value would be (3, 2, 4). On the other hand, using `torch.cat` with `dim=1` produces a result whose shape is `(3,8)`

In [27]:
# ==============================================================================
# Stacking tensors
# ==============================================================================
a = torch.randn((2, 2))
b = torch.randn((2, 2))
print("The original tesnor a is\n {}".format(a))
print("The original tesnor b is\n {}".format(b))
result = torch.stack((a, b), dim=1)
print("The shape of result is {}".format(result.shape))
print("The new tensor is\n {}".format(result))

The original tesnor a is
 tensor([[ 0.0695, -0.4278],
        [-0.4861, -0.7959]])
The original tesnor b is
 tensor([[-0.5204, -0.7523],
        [ 2.2930,  0.9971]])
The shape of result is torch.Size([2, 2, 2])
The new tensor is
 tensor([[[ 0.0695, -0.4278],
         [-0.5204, -0.7523]],

        [[-0.4861, -0.7959],
         [ 2.2930,  0.9971]]])


## Tensor Operations

### Mathematical Operations

#### With Scalars
In PyTorch, we perform mathematical operations with scalars in two ways:

* using operators like <font color='red'>`+`</font>, <font color='red'>`-`</font>, and <font color='red'>`*`</font>.
* using functions like <font color='red'>`add`</font>, <font color='red'>`sub`</font>, and <font color='red'>`mul`</font>.

In [28]:
# ==============================================================================
# Adding a scalar to all the values of a tensor
# ==============================================================================
a = torch.tensor([1,2,3])
b = a + 3
c = a.add(3)
print("Before adding: {}".format(a))
print("Adding 3 using '+': {}".format(b))
print("Adding 3 using 'add': {}".format(c))

Before adding: tensor([1, 2, 3])
Adding 3 using '+': tensor([4, 5, 6])
Adding 3 using 'add': tensor([4, 5, 6])


PyTorch supports most of the math functions under the native Python <font color='red'>`math`</font> module. You could find a complete list from the [official site](https://pytorch.org/docs/stable/torch.html#pointwise-ops).

##### In-place Operations
We notice all the above operations are not in-place, so we cannot change the tensor values directly. If we would like to perform in-place operations, instead, we use the defined functions for it. Mostly, it is the same function with added `_` at its end. For example, `add` & `add_` and `sin` & `sin_`

In [29]:
# ==============================================================================
# In-place operation
# ==============================================================================
a = torch.tensor([0, math.pi / 4, math.pi / 2, 3 * math.pi / 4])
print('a:')
print(a)
print(torch.sin(a))   # this operation creates a new tensor in memory
print(a)              # a has not changed

b = torch.tensor([0, math.pi / 4, math.pi / 2, 3 * math.pi / 4])
print('\nb:')
print(b)
print(torch.sin_(b))  # note the underscore
print(b)              # b has changed

a:
tensor([0.0000, 0.7854, 1.5708, 2.3562])
tensor([0.0000, 0.7071, 1.0000, 0.7071])
tensor([0.0000, 0.7854, 1.5708, 2.3562])

b:
tensor([0.0000, 0.7854, 1.5708, 2.3562])
tensor([0.0000, 0.7071, 1.0000, 0.7071])
tensor([0.0000, 0.7071, 1.0000, 0.7071])


In [30]:
# ==============================================================================
# In-place operations
# ==============================================================================
a = torch.ones(2, 2)
b = torch.rand(2, 2)

print('Before:')
print(a)
print(b)
print('\nAfter adding:')
print(a.add_(b))
print(a)
print(b)
print('\nAfter multiplying')
print(b.mul_(b))
print(b)

Before:
tensor([[1., 1.],
        [1., 1.]])
tensor([[0.9883, 0.4762],
        [0.7242, 0.0776]])

After adding:
tensor([[1.9883, 1.4762],
        [1.7242, 1.0776]])
tensor([[1.9883, 1.4762],
        [1.7242, 1.0776]])
tensor([[0.9883, 0.4762],
        [0.7242, 0.0776]])

After multiplying
tensor([[0.9768, 0.2268],
        [0.5245, 0.0060]])
tensor([[0.9768, 0.2268],
        [0.5245, 0.0060]])


#### Among Tensors

We have two mathematical operators among tensors
- **Element-wise**: using the same above operators and functions, like with scalars.<br>For example, `a+b` adds each element of `a` to its correspondence in `b`
- **Matrix Operation**: here we do matrix multiplication between tensors using<br>Notice: matrix dimension constraints should hold when using these operations
    - `mv`: multiplication between **matrix and vector** tensors
    - `mm`: multiplication between **matrix and matrix** tensors
    - `dot`: dot product of 2 **1D tensors**, vectors.

In [31]:
# ==============================================================================
# Element wise operations
# ==============================================================================
a = torch.tensor([1, 2, 3])
b = torch.tensor([2, 4, 6])

c = a * b
print("The multiple between a an b is {}".format(c))

c = a.mul(b)
print("The multiple between a an b is {}".format(c))

e = torch.tensor([[1, 2], [3, 4]])
f = torch.tensor([[2, 2], [2, 2]])

g = e*f 
print("The multiple between e an f is {}".format(g))

The multiple between a an b is tensor([ 2,  8, 18])
The multiple between a an b is tensor([ 2,  8, 18])
The multiple between e an f is tensor([[2, 4],
        [6, 8]])


In [32]:
# ==============================================================================
# Matrix-vector multiplication
# ==============================================================================
mat = torch.ones((2, 4))
print("The matrix is \n{}".format(mat))

print("="*30)
vec = torch.tensor([1, 2, 3, 4], dtype=torch.float)
print("The vector is \n{}".format(vec))

print("="*30)
result = mat.mv(vec)
print("The result is \n{}".format(result))

print("="*30)
result = torch.mv(mat, vec)
print("The result is \n{}".format(result))

The matrix is 
tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.]])
The vector is 
tensor([1., 2., 3., 4.])
The result is 
tensor([10., 10.])
The result is 
tensor([10., 10.])


In [33]:
# ==============================================================================
# Matrix-matrix multiplication
# ==============================================================================
mat1 = torch.ones((2, 4))
mat2 = torch.ones((4, 3))

result = torch.mm(mat1, mat2)
print("The result is \n {}".format(result))

print("="*30)
result = mat1.mm(mat2)
print("The result is \n {}".format(result))

The result is 
 tensor([[4., 4., 4.],
        [4., 4., 4.]])
The result is 
 tensor([[4., 4., 4.],
        [4., 4., 4.]])


In [34]:
# ==============================================================================
# vector-vector multiplication using dot product
# ==============================================================================
vec1 = torch.tensor([1, 2, 3, 4])
vec2 = torch.tensor([2, 3, 4, 5])

result = vec1.dot(vec2)
print("The result is \n {}".format(result))

print("="*30)
result = torch.dot(vec1, vec2)
print("The result is \n {}".format(result))

The result is 
 40
The result is 
 40


### Reduction Operations
These are operations performed on a particular dimension, default is `0`, over the group of values; it includes statistical and other operations

|Function Name | Purpose|
|---|---|
|`mean`|	Get the mean value of the tensor in the given dimension.|
|`sum`|	Sum the values of the tensor over the given dimension.|
|`median`|	Get the median value of tensor in the given dimension.|
|`std`|	Compute the standard deviation of the tensor over the given dimension.|
|`prod`|	Product the values of the tensor over the given dimension.|
|`cumsum`|	Cumulative sum of values of the tensor over the given dimension.|

In [35]:
# ==============================================================================
# Use the mean and sum to demonstrate their usage
# ==============================================================================
a = torch.randn((3,4))
print("The original tensor is \n {}".format(a))

# ==============================================================================
# We compute the mean of all the values per column, dim 1
# ==============================================================================
print("="*30)
b = torch.mean(a, dim=1)
print("The mean value of dim=1 \n {}".format(b))

# ==============================================================================
# We sum all the values per row, dim 0
# ==============================================================================
print("="*30)
c = torch.sum(a, dim=0)
print("The sum value of dim=0 \n {}".format(c))

The original tensor is 
 tensor([[ 0.2359,  0.7787, -0.1732, -0.1074],
        [ 1.9456,  0.4525,  0.1014,  0.3339],
        [ 1.6279,  1.0423, -0.6320,  1.4610]])
The mean value of dim=1 
 tensor([0.1835, 0.7084, 0.8748])
The sum value of dim=0 
 tensor([ 3.8094,  2.2735, -0.7038,  1.6875])


### Logical Operations

|Function	| Purpose|
|---|---|
|`lt`|	Less than|
|`le`|	Less than or equal to|
|`gt`|	Greater than|
|`ge`|	Greater than or equal to|
|`eq`|	Equal to|
|`ne`|	Not Equal to|

In [36]:
# ==============================================================================
# Demonstrate the logical operations
# ==============================================================================
a = torch.randn((3,4))
print("The original tensor is \n {}".format(a))

print("="*30)
print("The comparison between a tensor and a single value.\n")
b = torch.lt(a, 0.5)
print("The element is less than 0.5 \n {}".format(b))

print("="*30)
c = torch.randn((3, 4))
print("The comparison between two tensors.\n")
d = torch.gt(a, c)
print("The comparison result between tesnor a and c \n {}".format(d))

The original tensor is 
 tensor([[ 2.3482,  0.1805, -0.5357,  1.2000],
        [-0.6827, -0.1046, -0.9332, -0.8011],
        [-0.1352,  0.0627,  0.9978, -1.1855]])
The comparison between a tensor and a single value.

The element is less than 0.5 
 tensor([[False,  True,  True, False],
        [ True,  True,  True,  True],
        [ True,  True, False,  True]])
The comparison between two tensors.

The comparison result between tesnor a and c 
 tensor([[ True, False,  True,  True],
        [ True, False, False,  True],
        [False,  True,  True, False]])


## Saving and Loading Tensors

### Saving a single tensor

The **model weights**, as we will see, are mostly **saved** to be re-used without performing training again. In such case, we would typically store the tensors representing the weights. Below is a demonstration of how to save a single tensor. The file extension is usually `.pt`

In [37]:
# ==============================================================================
# Saving the file <a> into a location: here ./tensor.pt
# ==============================================================================
a = torch.tensor([1, 2, 3])
torch.save(a, "./tensor.pt")

### Loading tensors from file

It is simply the reverse of the saving operation. We just need to specify the location.

In [38]:
# ==============================================================================
# Loading the previously saved tesnor
# ==============================================================================
b = torch.load("./tensor.pt")
print("The tensor b is {}".format(b))

The tensor b is tensor([1, 2, 3])


### Saving Multiple Tensors

We use `save` not only to store a tensor, but also to save other stuctures like dictionaries. Below we use it to save a dictionary of multiple tensors

In [39]:
# ==============================================================================
# Use save to store a dictionary of tensors
# ==============================================================================
# m is a key-value structure to store variables.
# In this example, "t1" is the key, and tensor([1, 2, 3]) is the value.
m = {}
m["t1"] = torch.tensor([1, 2, 3])
m["t2"] = torch.tensor([2, 4, 6])
torch.save(m, "./m_tensor.pt")

m2 = torch.load("./m_tensor.pt")
print("The tensor map is {}".format(m2))

The tensor map is {'t1': tensor([1, 2, 3]), 't2': tensor([2, 4, 6])}


## GPU

First, we should check whether a GPU is available, with the <font color='red'>`is_available()`</font> method.

**Note: If you do not have a CUDA-compatible GPU and CUDA drivers installed, the executable cells in this section will not execute any GPU-related code.**

In [40]:
# ==============================================================================
# Checking whether a GPU is available
# ==============================================================================
if torch.cuda.is_available():
    print('We have a GPU!')
else:
    print('Sorry, CPU only.')

Sorry, CPU only.


Once we've determined that one or more GPUs is available, we need to put our data someplace where the GPU can see it. Your CPU does computation on data in your computer's RAM. Your GPU has dedicated memory attached to it. Whenever you want to perform a computation on a device, you must move *all* the data needed for that computation to memory accessible by that device. (Colloquially, "moving the data to memory accessible by the GPU" is shorted to, "moving the data to the GPU".)

### Creating Tensor on GPU
We can specify the tensor in which we would like to create our tensor on using the `device` argument as below

In [41]:
# ==============================================================================
# Creating a tensor on a particular device
# ==============================================================================
if torch.cuda.is_available():
    gpu_rand = torch.rand(2, 2, device='cuda')
    print(gpu_rand)
else:
    print('Sorry, CPU only.')

Sorry, CPU only.


By default, new tensors are created on the CPU, so we have to specify when we want to create our tensor on the GPU with the optional <font color='red'>`device`</font> argument. You can see when we print the new tensor, PyTorch informs us which device it's on (if it's not on CPU).

In [42]:
# ==============================================================================
# Store the available device in a string to be used within your code
# ==============================================================================
if torch.cuda.is_available():
    my_device = torch.device('cuda')
else:
    my_device = torch.device('cpu')
print('Device: {}'.format(my_device))

x = torch.rand(2, 2, device=my_device)
print(x)

Device: cpu
tensor([[0.1986, 0.1779],
        [0.6366, 0.2301]])


You can query the number of GPUs with <font color='red'>`torch.cuda.device_count()`</font>. If you have more than one GPU, you can specify them by index: <font color='red'>`device='cuda:0'`</font>, <font color='red'>`device='cuda:1'`</font>, etc. That is if you have multiple GPUs, then you can use <font color='red'>`cuda:0`</font> referring to 1st one, <font color='red'>`cuda:1`</font> referring to 2nd, or <font color='red'>`cuda:2`</font> to refer to the 3rd, etc.

### Casting to different device

We can use `to` to change a tensor from device to another

In [43]:
# ==============================================================================
# Change the tensor from CPU to GPU if it exists
# ==============================================================================
device = torch.device("cuda:0" if torch.cuda.is_available() else "cpu")
a = torch.tensor([1, 2, 3])
c = a.to(device)

**Note**: *all of the tensors must be on the same device*.

### Getting device

- `device` is used to return the tensor device
- `is_cdua` is a boolean value to indicate whether the tensor is on the GPU or not

In [44]:
# ==============================================================================
# Check the device
# ==============================================================================
a = torch.randn((2, 3, 4), dtype=torch.float)
print("The GPU is {}.\n".format(a.is_cuda))
print("The device is {}.".format(a.device))

The GPU is False.

The device is cpu.
